[package]
name = "UltraFastFileSearch"
version = "0.1.1"
edition = "2021"
build = "build.rs"
description = "Read Directories & Files"

# Specify the library crate
[lib]
name = "UltraFastFileSearch_library"
path = "src/lib.rs"

# Main binary
[[bin]]
name = "uffs"
path = "src/main.rs"

# CLI tool binary
[[bin]]
name = "uffs_cli"
path = "src/bin/cli.rs"

[dependencies]
rayon = "1.10.0"
tokio = { version = "1.42.0", features = ["full"] }
tokio-stream = { version = "0.1.17", features = ["fs"] }
async-std = "1.13.0"
sysinfo = { version = "0.33.0", default-features = true, features = ["linux-tmpfs"] }
threadpool = "1.8.1"
flume = "0.11.1"
ignore = "0.4.23"
thread_local = "1.1.8"
async-recursion = "1.1.1"
futures = "0.3.31"
chrono = "0.4.39"
either = "1.13.0"
num_cpus = "1.16.0"
num-format = "0.4.4"
colored = "2.1.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["time", "env-filter"] }
tracing-appender = "0.2.3"
dirs-next = "2.0.0"
time = "0.3.37"
once_cell = "1.20.2"
async-trait = "0.1.83"
jwalk = "0.8.1"
tempfile = "3.14.0"
rand = "0.8.5"
anyhow = "1.0.94"
serde = { version = "1.0.216", features = ["derive"] }
log = "0.4.22"
thiserror = "2.0.6"
miette = "7.4.0"
clap = { version = "4.5.17", features = ["derive"] }
walkdir = "2.5.0"
bitflags = "2.6.0"
serde_json = "1.0.133"
wmi = "0.14.2"
#windows = { version = "0.58.0", features = ["Win32_Foundation", "Win32_System_Ioctl", "Win32_System_SystemServices", "Win32_System_Com", "Win32_System_Wmi", "Win32_System_Rpc", "Win32_System_Threading", "Win32_System_Ole", "implement", "Win32_Storage_FileSystem",    "Win32_System_WindowsProgramming"] }
windows = { version = "0.58.0", features = ["Win32_Storage_FileSystem","Win32_System_Ioctl", "Win32_Storage", "implement", "Win32_Foundation", "Win32_System_Com", "Win32_System_Wmi"] }
windows-core = "0.58.0"

[build-dependencies]
toml = "0.8.19"
dirs-next = "2.0.0"
chrono = "0.4.39"
time = "0.3.37"
log = "0.4.22"
simplelog = "0.12.2"

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"
rayon = "1.10.0"
lazy_static = "1.5.0"

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
incremental = true
codegen-units = 16
rpath = false

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 1
lto = true
panic = "abort"
strip = "symbols"

[profile.debug-optimized]
inherits = "dev"
opt-level = 2
debug = true
debug-assertions = true
overflow-checks = true

[profile.bench]
inherits = "release"
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 1
lto = "thin"
strip = "debuginfo"

